/**
 * Every drawing in utils/icons/tree_icons, by name.
 *
 * ## Why the list is here and not fetched
 *
 * The icons are static files served by the backend, so the browser can draw any
 * one of them by name and has no way of knowing which names exist. Matching a
 * skill's title to a drawing needs that set — see skills/iconMatch — and a
 * request for a directory listing would be a network round trip, an endpoint,
 * and a failure mode, in exchange for a fact that only changes when somebody
 * adds a file to the repository.
 *
 * ## It is generated, and checked
 *
 * Written from the folder, and `npm run check:trees` fails if the two have
 * drifted — it already reads that directory to catch icons named in a tree with
 * no file behind them, so it is the natural place to catch a file with no name
 * in here. The failure names the fix. Nothing else in the app should enumerate
 * icons: `iconUrl` in skills/subjectTrees still takes any string and falls back,
 * because a tree is allowed to name a drawing this list has not caught up with.
 */

/** Icon file names, without the extension, sorted. */
export const ICON_NAMES: readonly string[] = [
  'ab-test', 'accessibility', 'accompany', 'acid', 'admin', 'advert', 'aerobic', 'aggregate',
  'agility', 'agreement', 'algebra-x', 'allocation', 'alphabet', 'amp', 'analytics', 'aperture',
  'api', 'apply', 'archive', 'argument', 'arithmetic', 'arrangement', 'arrays', 'asset-classes',
  'atmosphere', 'atoms', 'attention', 'attention-span', 'audience', 'audio-edit', 'auth',
  'autodidact', 'automation', 'automaton', 'available', 'average', 'avoidance', 'backprop',
  'backup', 'balance-food', 'balance-scale', 'balance-sheet', 'banking', 'barbell', 'barre',
  'basis', 'bass', 'bass-clef', 'batch', 'battery', 'bayes', 'beauty', 'bedtime', 'behaviour',
  'bell-curve', 'belt', 'bench-press', 'bend', 'benzene', 'binary-search', 'biology',
  'biomolecule', 'birthday', 'body-scan', 'bond', 'book', 'booking', 'bookkeeping', 'boolean',
  'boom-mic', 'boost', 'boredom', 'boundary', 'brace', 'brain', 'branch', 'brand', 'bread',
  'break', 'breath', 'brief', 'bronze', 'browser', 'brush', 'bst', 'budget', 'buffer', 'burnout',
  'business-model', 'cache', 'calculus', 'calendar-block', 'calm', 'camera', 'camera-move',
  'canon', 'capo', 'carbs', 'career', 'career-change', 'carry', 'cashflow', 'causal', 'cdn',
  'cells', 'central-bank', 'change', 'change-over-time', 'character', 'chart-bars', 'checklist',
  'chem-equation', 'chemistry', 'choice', 'chord-change', 'chord-shape', 'chords', 'circuit',
  'citation', 'clapper', 'clarity', 'clean-data', 'cleaning', 'client-state', 'climate', 'cloud',
  'clt', 'clusters', 'coaching', 'cognition', 'colour-grade', 'colour-wheel', 'column',
  'combinations', 'compare', 'compass', 'compassion', 'compile', 'complexity', 'components',
  'compose', 'composition', 'compound', 'compress', 'compressor', 'concept-map', 'concurrency',
  'conditional-prob', 'conditionals', 'conflict', 'connected-components', 'constellation',
  'constraint', 'construction', 'content', 'context', 'continuity', 'contract', 'contradiction',
  'contrast', 'control-var', 'conversation', 'cooking', 'coordinate-plane', 'copywriting',
  'core-skill', 'correlation', 'cosmos', 'counting', 'coverage', 'craft', 'credit-card',
  'critique', 'cross-train', 'css', 'cull', 'culture', 'currency', 'customer', 'cycle',
  'data-structures', 'database', 'datagram', 'dataset', 'daw', 'day-plan', 'deadlift', 'debate',
  'debugging', 'decision', 'decision-tree', 'decline', 'declutter', 'deep-time', 'deep-work',
  'deficit', 'definition', 'delay', 'delegate', 'deload', 'deploy', 'depth', 'derivatives',
  'design', 'design-system', 'determinant', 'development', 'device-off', 'diagonal', 'diet',
  'dilemma', 'directing', 'discipline', 'discussion', 'distraction', 'distribution', 'diversify',
  'dna', 'dns', 'document-store', 'documentary', 'dom', 'dot-product', 'draft', 'drawing',
  'drum-machine', 'dumbbell', 'dynamic-programming', 'dynamics', 'ear-training', 'earth-layers',
  'earth-system', 'easel', 'econ-data', 'econ-lens', 'economics', 'ecosystem', 'edit-pen',
  'effect-size', 'effort', 'egg', 'eigen', 'elasticity', 'electric-field', 'em-wave', 'email',
  'emotion', 'empire', 'employment', 'encryption', 'energy', 'energy-balance', 'enlightenment',
  'entropy', 'enzyme', 'eq', 'equations', 'equilibrium', 'era', 'errand', 'error-bars',
  'error-log', 'error-types', 'essay', 'estimate', 'ethics', 'evidence', 'evolution', 'exam',
  'expectations', 'experiment', 'explain', 'exposure', 'fairness', 'fallacy', 'fats', 'feast',
  'feature', 'feedback', 'fees', 'fibre', 'figure', 'filesystem', 'film', 'fingering',
  'fingerstyle', 'firewall', 'flag', 'flash', 'flashcards', 'flow', 'flow-state', 'fluency',
  'fluid', 'focus', 'focus-lens', 'focus-log', 'folds', 'follow-up', 'food-safety', 'forces',
  'forensics', 'form', 'form-3d', 'form-check', 'fractions', 'frame', 'free-body', 'fretboard',
  'friction', 'friends', 'fuel', 'functions', 'functions-graph', 'fund', 'funnel', 'gait',
  'galaxy', 'game-theory', 'garden', 'gauge', 'gdp', 'gem', 'gene-edit', 'genetics', 'genre',
  'geography', 'geometry', 'gesture', 'globe', 'goal', 'gold', 'gradient', 'graduation', 'grain',
  'grammar', 'graph-nodes', 'gravity', 'greedy', 'grid', 'grid-time', 'groceries', 'group-travel',
  'growth-curve', 'guitar', 'habit', 'hands', 'handshake', 'harmony', 'harmony-voices', 'hash',
  'hash-map', 'heap', 'heat', 'hierarchy', 'hill', 'hinge', 'hiring', 'historiography', 'history',
  'homecoming', 'homeostasis', 'horizon', 'html', 'http', 'hypertrophy', 'hypothesis',
  'iconography', 'idea', 'idiom', 'imagery', 'immune', 'implication', 'implicit', 'improvise',
  'in-progress', 'inbox', 'incentive', 'incident', 'income', 'index', 'induction', 'inequality',
  'inflation', 'injection', 'injury', 'ink', 'input-stream', 'insight', 'insurance', 'integrals',
  'interest', 'interleave', 'interrupt', 'interval-est', 'intervals', 'intervals-training',
  'interview', 'invention', 'inverse', 'ip-address', 'iso', 'isolation', 'jobsearch', 'join',
  'journal', 'kernel', 'key-id', 'key-signature', 'kickoff', 'kinematics', 'knife', 'knowledge',
  'kpi', 'lab', 'lab-notebook', 'label', 'labels', 'landing-page', 'landscape', 'latency',
  'laundry', 'layers', 'layout', 'leadership', 'learning', 'least-squares', 'ledger', 'leftovers',
  'legato', 'lemon', 'lens', 'library', 'life', 'light', 'lighting', 'limits', 'line-quality',
  'linear-equation', 'linked-list', 'listening', 'literature', 'load-balancer', 'locked',
  'logarithm', 'logic', 'long-run', 'longevity', 'loops', 'macros', 'magnet', 'magnifier',
  'maintain', 'malware', 'management', 'manuscript', 'map', 'market', 'market-failure',
  'marketing', 'master', 'master-study', 'mastered', 'materials', 'matrices', 'meal-plan',
  'meal-prep', 'meal-time', 'meaning', 'measure-art', 'measurement', 'media', 'meditation',
  'meeting', 'membrane', 'memory', 'message', 'metaphysics', 'metronome', 'micronutrients',
  'microphone', 'microscope', 'midi', 'migration', 'milestone', 'mind', 'mise', 'mitosis',
  'mixer', 'mnemonic', 'mobility', 'model', 'modes', 'modular', 'mole', 'molecule', 'momentum',
  'monument', 'motion', 'multiple-tests', 'museum', 'music-note', 'mutation', 'narrative', 'nat',
  'nature', 'negative-numbers', 'negotiate', 'network', 'network-people', 'neural-net', 'neuron',
  'normalise', 'notebook', 'notes', 'notification-off', 'nutrition', 'objects', 'observe',
  'ocean', 'onboard', 'one-on-one', 'opening', 'opportunity', 'optics', 'orbit', 'orbital',
  'orders', 'organs', 'orthogonal', 'outline', 'overfit', 'overload', 'pacing', 'package',
  'packet', 'palette', 'pan', 'paper', 'parabola', 'paragraph', 'party', 'passport', 'path-route',
  'peak', 'pedal', 'peer-review', 'pentatonic', 'pentest', 'percent', 'perception', 'performance',
  'periodic', 'permission', 'personality', 'perspective', 'philosophy', 'phishing', 'phonetics',
  'photo-edit', 'photosynthesis', 'phrase', 'phrasebook', 'physics', 'piano-keys', 'pick',
  'pigeonhole', 'piggy-bank', 'pipeline', 'pitch', 'plan', 'planet', 'plateau', 'plates', 'poem',
  'pointers', 'politics', 'polyrhythm', 'population', 'portfolio', 'portrait', 'positioning',
  'posterior', 'posture', 'pot', 'power', 'power-chord', 'practice', 'precalculus', 'precision',
  'presenting', 'price-tag', 'primes', 'print', 'priority', 'probability', 'problem',
  'problem-set', 'process', 'progress-log', 'progressions', 'project', 'projection', 'proof',
  'property', 'protein', 'protein-food', 'prototype', 'proxy', 'psychology', 'publish', 'pullup',
  'punctuation', 'pushup', 'puzzle', 'quantifier', 'quantum', 'query', 'query-plan', 'question',
  'queue', 'race', 'range', 'rank', 'rank-test', 'rate', 'raw-file', 'reaction', 'reading',
  'rebalance', 'record', 'recovery', 'recurrence', 'recursion', 'recycle', 'redox', 'reference',
  'reflect', 'registers', 'regression', 'relation', 'release', 'reliable', 'remote', 'repair',
  'replicate', 'report', 'reps', 'research', 'resonance', 'resources', 'respiration',
  'responsive', 'rest', 'resume', 'retain', 'retention', 'retirement', 'retrieval', 'reverb',
  'revise', 'revision', 'revolution', 'rhythm', 'ribosome', 'risk', 'ritual', 'rock', 'rocket',
  'rotation', 'route', 'router', 'routine', 'routing', 'running', 'safety', 'salt', 'sampler',
  'sampling', 'sanitise', 'satiety', 'sauce', 'scales', 'scarcity', 'scene', 'schema',
  'scientific-method', 'script-attack', 'scrutiny', 'search-engine', 'searching', 'security',
  'self-manage', 'sentence', 'sequence', 'series', 'series-photo', 'serve-model', 'server',
  'sets', 'setting', 'shading', 'shallow-work', 'shapes', 'shard', 'shield', 'shot', 'shutter',
  'sight-read', 'silver', 'single-task', 'sketchbook', 'skill-up', 'sleep', 'slow-travel',
  'social', 'social-contract', 'social-media', 'society', 'socket', 'solar-system', 'solo',
  'solution', 'songbook', 'sorting', 'sound', 'sound-bank', 'sound-design', 'source-doc',
  'spacetime', 'span', 'spark', 'speaking', 'spectrum', 'spices', 'split-data',
  'sports-nutrition', 'squat', 'stack', 'staff', 'stakeholder', 'star', 'star-life',
  'states-matter', 'statistics', 'still-life', 'stock-chart', 'story-arc', 'storyboard', 'strata',
  'strategy', 'streak', 'street', 'street-food', 'stress', 'strings', 'strum', 'study',
  'study-design', 'study-group', 'study-plan', 'style', 'stylise', 'suitcase', 'summary',
  'sunlight', 'supplement', 'supply-chain', 'supply-demand', 'surplus', 'sustain', 'svd',
  'switch-cost', 'syntax', 'synth', 'system', 'table', 'tablet', 'taper', 'target', 'tax',
  'tax-shelter', 'taxonomy', 'telescope', 'tempo', 'tense', 'terminal', 'testimony', 'texture',
  'theatre', 'theme', 'therapy', 'thermometer', 'thesis', 'thought-exp', 'thoughts', 'threads',
  'threat', 'threshold', 'tidy', 'time-series', 'timeline', 'timeline-edit', 'timer', 'titration',
  'tls', 'todo', 'token', 'tone', 'toolbox', 'trace', 'trade', 'tradition', 'training-plan',
  'transaction', 'transfer', 'transform', 'transition', 'translate', 'transport', 'travel',
  'traversal', 'treasury', 'tree-structure', 'triad', 'trie', 'trigonometry', 'trim', 'trophy',
  'trust', 'tuning-peg', 'tunnel', 'two-hands', 'types', 'typography', 'understanding',
  'unit-econ', 'units', 'unlocked', 'usability', 'user-research', 'value-scale', 'variables',
  'vault', 'vector-add', 'vectors', 'vegetable', 'version-control', 'view', 'viewpoint',
  'visibility', 'vision', 'vocabulary', 'vocal-health', 'voice-print', 'volcano', 'volume',
  'vowel', 'walking', 'warehouse', 'warmup', 'warning', 'water', 'waveform', 'waves', 'weather',
  'weekly-review', 'white-balance', 'whitespace', 'wireframe', 'wireless', 'workload',
  'workspace', 'writing', 'xp-bolt', 'yoga', 'zones',
];

/** The same set, for the lookups skills/iconMatch does one after another. */
export const ICONS = new Set(ICON_NAMES);
