import type { SubjectTree } from './types';
import { done, prog, open, lock } from './types';

export const ALGO: SubjectTree = {
  id: 'algorithms',
  title: 'Algorithms & Data Structures',
  blurb: 'The structures worth knowing, and the moves that run over them.',
  parent: 'coding',
  nodes: [
    { id: 'a.arrays', name: 'Arrays', icon: 'arrays', tier: 'foundation', core: true, state: done, percent: 100, xp: 1500,
      desc: 'A block of values in order, reachable instantly by position. Everything else is built on understanding why reading by index is free and inserting in the middle is not.' },
    { id: 'a.strings', name: 'Strings', icon: 'strings', tier: 'foundation', requires: ['a.arrays'], state: done, percent: 100, xp: 1400,
      desc: 'Arrays of characters with their own set of classic problems. Most string questions are really array questions wearing different clothes, which is worth noticing early.' },
    { id: 'a.bigo', name: 'Big-O Notation', icon: 'complexity', tier: 'beginner', core: true, requires: ['a.arrays'], state: prog, percent: 70, xp: 1800,
      desc: 'A way of describing how the work grows as the input does, ignoring constants and hardware. It is the only comparison between two approaches that survives a faster machine.' },
    { id: 'a.sets', name: 'Sets', icon: 'sets', tier: 'beginner', requires: ['a.arrays'], state: prog, percent: 60, xp: 1300,
      desc: 'A collection with no duplicates and instant membership tests. Reaching for one is the single most common way an accidental n-squared loop becomes linear.' },
    { id: 'a.linked', name: 'Linked Lists', icon: 'linked-list', tier: 'beginner', requires: ['a.arrays'], state: prog, percent: 65, xp: 1600,
      desc: 'Values joined by references rather than by position, so inserting and removing are cheap but reaching the tenth item is not. Mostly valuable now as the place where pointer thinking is learned.' },
    { id: 'a.stacks', name: 'Stacks & Queues', icon: 'stack', tier: 'beginner', requires: ['a.linked'], state: prog, percent: 50, xp: 1700,
      desc: 'Two disciplines of access: last-in-first-out, and first-in-first-out. Which one a problem wants usually decides the whole shape of the solution, as with depth-first against breadth-first search.' },
    { id: 'a.hash', name: 'Hash Maps', icon: 'hash-map', tier: 'intermediate', core: true, requires: ['a.sets'], state: open, percent: 25, xp: 2100,
      desc: 'Storing and finding values by key in roughly constant time. The trade is memory for speed, and the assumption underneath is that your keys hash evenly — which is why collisions are worth understanding.' },
    { id: 'a.twopointer', name: 'Two Pointers', icon: 'pointers', tier: 'intermediate', requires: ['a.strings', 'a.bigo'], state: open, percent: 20, xp: 1700,
      desc: 'Walking a sequence with two indices that move under different rules. Turns a great many quadratic scans into a single pass, especially on sorted data.' },
    { id: 'a.sliding', name: 'Sliding Window', icon: 'measurement', tier: 'intermediate', requires: ['a.twopointer'], state: lock, percent: 0, xp: 1800,
      desc: 'Keeping a running view of a contiguous stretch, growing and shrinking it instead of recomputing. The pattern behind almost every "longest substring such that" problem.' },
    { id: 'a.recursion', name: 'Recursion', icon: 'recursion', tier: 'intermediate', core: true, requires: ['a.stacks'], state: open, percent: 15, xp: 2300,
      desc: 'A function defined in terms of a smaller version of the same problem. Write the base case first and trust the recursive call — trying to trace every level in your head is what makes it feel hard.' },
    { id: 'a.sorting', name: 'Sorting', icon: 'sorting', tier: 'intermediate', requires: ['a.hash'], state: lock, percent: 0, xp: 1900,
      desc: 'Putting things in order, and the reason n log n is the floor for comparison-based methods. In practice you call the built-in one; knowing how it works is for choosing keys and predicting cost.' },
    { id: 'a.searching', name: 'Binary Search', icon: 'binary-search', tier: 'intermediate', requires: ['a.sorting'], state: lock, percent: 0, xp: 1800,
      desc: 'Halving the search space each step on ordered data. The real power is searching over an answer rather than an array — the version most people meet years after the basic one.' },
    { id: 'a.bitwise', name: 'Bit Manipulation', icon: 'kernel', tier: 'intermediate', requires: ['a.bigo'], state: lock, percent: 0, xp: 1600,
      desc: 'Working directly with the binary digits of a number. Niche but occasionally decisive, and the fastest way to represent a small set of on-or-off facts.' },
    { id: 'a.heaps', name: 'Heaps & Priority Queues', icon: 'heap', tier: 'advanced', requires: ['a.sorting'], state: lock, percent: 0, xp: 2000,
      desc: 'A structure that always hands you the smallest or largest item next, without keeping everything sorted. The engine inside scheduling, streaming top-k, and shortest-path algorithms.' },
    { id: 'a.trees', name: 'Trees', icon: 'tree-structure', tier: 'advanced', requires: ['a.recursion'], state: lock, percent: 0, xp: 2200,
      desc: 'Branching structures with a single root and no cycles. Nearly every operation is naturally recursive, which makes them the place recursion finally feels obvious rather than clever.' },
    { id: 'a.bst', name: 'Binary Search Trees', icon: 'bst', tier: 'advanced', requires: ['a.trees', 'a.searching'], state: lock, percent: 0, xp: 2200,
      desc: 'A tree that keeps its values ordered, so search, insert and delete are logarithmic — as long as it stays balanced. What happens when it does not is the whole reason self-balancing trees exist.' },
    { id: 'a.tries', name: 'Tries', icon: 'trie', tier: 'advanced', requires: ['a.trees', 'a.strings'], state: lock, percent: 0, xp: 2100,
      desc: 'A tree keyed by the characters of a word, so shared prefixes are stored once. The structure behind autocomplete and fast dictionary lookups.' },
    { id: 'a.unionfind', name: 'Union-Find', icon: 'network', tier: 'advanced', requires: ['a.trees'], state: lock, percent: 0, xp: 2100,
      desc: 'A structure for tracking which things are in the same group as merges happen. Tiny to implement, surprisingly fast, and exactly what connectivity and spanning-tree problems need.' },
    { id: 'a.backtracking', name: 'Backtracking', icon: 'branch', tier: 'advanced', requires: ['a.recursion'], state: lock, percent: 0, xp: 2400,
      desc: 'Building a solution one choice at a time and undoing a choice when it leads nowhere. Systematic brute force — and the skill is pruning branches early enough to make it finish.' },
    { id: 'a.greedy', name: 'Greedy', icon: 'greedy', tier: 'advanced', requires: ['a.sorting'], state: lock, percent: 0, xp: 2000,
      desc: 'Taking the locally best option each step and having that be globally right. It works far less often than it appears to, so the real skill is proving the greedy choice is safe.' },
    { id: 'a.dp', name: 'Dynamic Programming', icon: 'dynamic-programming', tier: 'expert', requires: ['a.backtracking', 'a.hash'], state: lock, percent: 0, xp: 2800,
      desc: 'Solving overlapping subproblems once and reusing the answers. Every DP is a recursion plus memory; write the recurrence in words before writing any code and most of the difficulty disappears.' },
    { id: 'a.graphs', name: 'Graphs', icon: 'graph-nodes', tier: 'advanced', requires: ['a.trees'], navTo: 'graphs', state: lock,
      desc: 'A subject of its own: traversal, shortest paths, spanning trees and flow, over networks of any shape.' },
    { id: 'a.contest', name: 'Competitive Programming', icon: 'race', tier: 'expert', requires: ['a.dp', 'a.greedy'], navTo: 'competitive-programming', state: lock,
      desc: 'A subject of its own: USACO and Codeforces — recognising the shape, then writing it fast.' },
  ],
};
