import type { SubjectTree } from './types';
import { open, lock } from './types';

export const CALCULUS: SubjectTree = {
  id: 'calculus',
  title: 'Calculus',
  blurb: 'Rates and areas — a subject the moment it stops being a single node.',
  parent: 'mathematics',
  nodes: [
    { id: 'k.limits', name: 'Limits', icon: 'limits', tier: 'advanced', core: true, state: open, percent: 30, xp: 2000,
      desc: 'What a function approaches as the input closes in on a value, whether or not it ever arrives. Every idea in calculus is defined in terms of this one, so it is worth more time than it usually gets.' },
    { id: 'k.continuity', name: 'Continuity', icon: 'functions-graph', tier: 'advanced', requires: ['k.limits'], state: open, percent: 10, xp: 1800,
      desc: 'A function with no jumps, holes or gaps — one you could draw without lifting the pen. The theorems that follow all quietly require it, which is why the exceptions matter.' },
    { id: 'k.deriv', name: 'Derivatives', icon: 'derivatives', tier: 'advanced', core: true, requires: ['k.continuity'], state: lock, percent: 0, xp: 2400,
      desc: 'The rate at which something changes at a single instant, defined as a limit of average rates. Being able to say what it means for a real quantity matters more than being able to compute it.' },
    { id: 'k.rules', name: 'Differentiation Rules', icon: 'equations', tier: 'advanced', requires: ['k.deriv'], state: lock, percent: 0, xp: 2100,
      desc: 'Product, quotient and chain — the shortcuts that make derivatives fast once you have done a few from first principles. The chain rule is the one that keeps being the culprit.' },
    { id: 'k.implicit', name: 'Implicit Differentiation', icon: 'implicit', tier: 'expert', requires: ['k.rules'], state: lock, percent: 0, xp: 2200,
      desc: 'Differentiating a relationship that is not written as y equals something. The trick is remembering that y is still a function of x, so the chain rule applies every time it appears.' },
    { id: 'k.optim', name: 'Optimization', icon: 'target', tier: 'expert', requires: ['k.rules'], state: lock, percent: 0, xp: 2300,
      desc: 'Finding the largest or smallest value something can take, by looking where the derivative is zero. The modelling is the hard half; the calculus is usually two lines.' },
    { id: 'k.related', name: 'Related Rates', icon: 'timer', tier: 'expert', requires: ['k.implicit'], state: lock, percent: 0, xp: 2200,
      desc: 'How fast one quantity changes given how fast another does, when the two are linked. Write the relationship first and differentiate with respect to time second — the reverse never works.' },
    { id: 'k.integral', name: 'Integrals', icon: 'integrals', tier: 'expert', requires: ['k.deriv'], state: lock, percent: 0, xp: 2500,
      desc: 'Adding up infinitely many infinitely small pieces to get an area, a total or an accumulation. Meeting it first as a Riemann sum is what stops it being an arbitrary new symbol.' },
    { id: 'k.ftc', name: 'The Fundamental Theorem', icon: 'star', tier: 'expert', requires: ['k.integral'], state: lock, percent: 0, xp: 2800,
      desc: 'That differentiation and integration undo each other. It is what turns integration from a limit you must compute into an antiderivative you can look up, and it deserves to feel surprising.' },
    { id: 'k.techniques', name: 'Integration Techniques', icon: 'puzzle', tier: 'expert', requires: ['k.ftc'], state: lock, percent: 0, xp: 2600,
      desc: 'Substitution, parts and partial fractions — the toolkit for integrals that do not yield directly. Recognising which to reach for is pattern matching that only practice builds.' },
    { id: 'k.applications', name: 'Areas & Volumes', icon: 'geometry', tier: 'expert', requires: ['k.techniques'], state: lock, percent: 0, xp: 2400,
      desc: 'Using integration for the area between curves and the volume of a solid of revolution. Sketch the region and the representative slice first; the integral then writes itself.' },
    { id: 'k.series', name: 'Series', icon: 'series', tier: 'mastery', requires: ['k.techniques'], state: lock, percent: 0, xp: 2700,
      desc: 'Infinite sums, and the tests that decide whether one settles on a finite value. A rare place where the answer is genuinely yes or no and the reasoning is the whole content.' },
    { id: 'k.taylor', name: 'Taylor Series', icon: 'spark', tier: 'mastery', requires: ['k.series'], state: lock, percent: 0, xp: 2900,
      desc: 'Approximating any well-behaved function by a polynomial built from its derivatives. This is how a calculator computes sine, and why the approximation gets worse away from the centre.' },
    { id: 'k.diffeq', name: 'Differential Equations', icon: 'physics', tier: 'mastery', requires: ['k.applications', 'k.taylor'], state: lock, percent: 0, xp: 3000,
      desc: 'Equations relating a quantity to its own rate of change, which is how nearly every physical law is written. Solving one means finding a whole function rather than a number.' },
  ],
};
