import type { SubjectTree } from './types';
import { done, prog, open, lock } from './types';

export const CODING: SubjectTree = {
  id: 'coding',
  title: 'Coding',
  blurb: 'The craft under every language — and where it forks into its own worlds.',
  group: 'Computing',
  nodes: [
    { id: 'c.vars', name: 'Variables', icon: 'variables', tier: 'foundation', core: true, state: done, percent: 100, xp: 2450,
      desc: 'A name bound to a value the program can read and change later. The whole idea is that the name stays put while what it holds moves, which is what lets you write one instruction that works on data you have not seen yet. Most early confusion is really about when the value changes, not about the name.' },
    { id: 'c.types', name: 'Types', icon: 'types', tier: 'foundation', core: true, requires: ['c.vars'], state: done, percent: 100, xp: 2100,
      desc: 'What kind of thing a value is — a number, a piece of text, a true-or-false. The type decides what the operators actually do, which is why adding two numbers and adding two strings look identical and mean completely different things.' },
    { id: 'c.ops', name: 'Operators', icon: 'arithmetic', tier: 'foundation', requires: ['c.types'], state: done, percent: 100, xp: 1400,
      desc: 'Arithmetic, comparison and logic: the small set of symbols that combine values into new ones. Precedence is the part worth learning properly, because a wrong assumption there produces an answer rather than an error.' },
    { id: 'c.io', name: 'Input & Output', icon: 'terminal', tier: 'foundation', requires: ['c.vars'], state: prog, percent: 85, xp: 1800,
      desc: 'Getting information in from a person, a file or another program, and sending something back. It is the first point where your code meets the world, so it is also the first place your assumptions about what arrives get tested.' },
    { id: 'c.cond', name: 'Conditionals', icon: 'conditionals', tier: 'beginner', requires: ['c.ops'], state: done, percent: 90, xp: 1900,
      desc: 'Choosing between paths based on whether something is true. Writing the branch is easy; writing a condition that says exactly what you meant, including at the edges, is the actual skill.' },
    { id: 'c.loops', name: 'Loops', icon: 'loops', tier: 'beginner', requires: ['c.cond'], state: prog, percent: 75, xp: 2000,
      desc: 'Doing the same work repeatedly — over a range, over a collection, or until something becomes true. The two questions that matter are what changes each time round and what makes it stop.' },
    { id: 'c.lists', name: 'Lists & Collections', icon: 'arrays', tier: 'beginner', requires: ['c.loops'], state: prog, percent: 55, xp: 1900,
      desc: 'Holding many values under one name and working through them. Once you can build, filter and transform a list, most programs stop being about single values entirely.' },
    { id: 'c.strings', name: 'Text & Strings', icon: 'strings', tier: 'beginner', requires: ['c.lists'], state: open, percent: 30, xp: 1600,
      desc: 'Text as data you can slice, search, split and rebuild. It looks simple because you can read it, but encoding, whitespace and the cost of joining in a loop catch nearly everyone once.' },
    { id: 'c.fns', name: 'Functions', icon: 'functions', tier: 'beginner', core: true, requires: ['c.loops', 'c.io'], state: prog, percent: 60, xp: 2600,
      desc: 'A named piece of work with inputs and a result, callable from anywhere. This is the first real tool for managing size: it lets you stop holding the whole program in your head and think about one job at a time.' },
    { id: 'c.style', name: 'Readable Code', icon: 'book', tier: 'beginner', requires: ['c.fns'], state: open, percent: 25, xp: 1300,
      desc: 'Naming, shape and structure chosen so the next reader — usually you, months later — understands it without running it. Not decoration: unreadable code is where most bugs hide.' },
    { id: 'c.debug', name: 'Debugging', icon: 'debugging', tier: 'intermediate', requires: ['c.cond'], recommends: ['c.io'], state: prog, percent: 60, xp: 1700,
      desc: 'Finding out what the program is really doing instead of what you assumed. The method is the skill: reproduce it reliably, form one hypothesis, test that hypothesis, and only then change a line.' },
    { id: 'c.err', name: 'Error Handling', icon: 'error-types', tier: 'intermediate', requires: ['c.debug'], state: open, percent: 20, xp: 1600,
      desc: 'Deciding in advance what should happen when something fails — a missing file, bad input, a network that vanished. The hard judgement is which errors to handle where, and which should be allowed to stop the program loudly.' },
    { id: 'c.ds', name: 'Data Structures', icon: 'data-structures', tier: 'intermediate', requires: ['c.fns', 'c.lists'], state: open, percent: 20, xp: 2400,
      desc: 'Choosing the shape that fits the work: a list for order, a map for lookup, a set for membership. The choice is usually the difference between a fast program and a slow one, long before any clever algorithm is involved.' },
    { id: 'c.oop', name: 'Objects & Classes', icon: 'objects', tier: 'intermediate', requires: ['c.fns'], state: open, percent: 10, xp: 2300,
      desc: 'Bundling data together with the operations that belong to it, so a thing knows how to look after itself. Powerful and easy to overuse — plenty of code is clearer as plain functions over plain data.' },
    { id: 'c.modules', name: 'Modules & Packages', icon: 'package', tier: 'intermediate', requires: ['c.style'], state: open, percent: 15, xp: 1500,
      desc: 'Splitting a program across files with deliberate boundaries, and pulling in code other people wrote. What to expose and what to keep private is the decision that keeps a growing project navigable.' },
    { id: 'c.files', name: 'Files & Persistence', icon: 'filesystem', tier: 'intermediate', requires: ['c.err'], state: lock, percent: 0, xp: 1700,
      desc: 'Storing data so it survives the program exiting, and reading it back intact. Most of the difficulty is not writing the bytes but handling the cases where the file is missing, half-written or being changed by something else.' },
    { id: 'c.git', name: 'Version Control', icon: 'version-control', tier: 'intermediate', requires: ['c.debug'], state: open, percent: 15, xp: 1500,
      desc: 'Keeping every version of the work, with the ability to see what changed, why, and to go back. Branching turns it from a backup into a way of trying things without risk.' },
    { id: 'c.test', name: 'Testing', icon: 'checklist', tier: 'intermediate', requires: ['c.fns', 'c.err'], state: lock, percent: 0, xp: 2000,
      desc: 'Code that checks your code, so a change that breaks something old tells you immediately. The value is not proving correctness — it is the freedom to change things without fear.' },
    { id: 'c.refactor', name: 'Refactoring', icon: 'layers', tier: 'advanced', requires: ['c.test', 'c.style'], state: lock, percent: 0, xp: 2200,
      desc: 'Changing the shape of code without changing what it does. Done in small steps behind tests, it is how a program that grew badly becomes one you can keep working in.' },
    { id: 'c.async', name: 'Asynchronous Code', icon: 'concurrency', tier: 'advanced', requires: ['c.err', 'c.fns'], state: lock, percent: 0, xp: 2500,
      desc: 'Work that starts now and finishes later — a download, a timer, a database call — without freezing everything else. The mental shift is that the order lines appear in stops being the order they run in.' },
    { id: 'c.perf', name: 'Performance', icon: 'complexity', tier: 'advanced', requires: ['c.ds'], state: lock, percent: 0, xp: 2300,
      desc: 'Making a program fast enough, starting by measuring rather than guessing. Almost all real gains come from doing less work, not from micro-optimising the work you are already doing.' },
    { id: 'c.design', name: 'Program Design', icon: 'compass', tier: 'expert', core: true, requires: ['c.refactor', 'c.modules'], state: lock, percent: 0, xp: 3000,
      desc: 'Deciding what the pieces of a system are and how they should depend on each other, before there is much code. This is the skill that separates a program that survives its second year from one that gets rewritten.' },
    { id: 'c.web', name: 'Web Development', icon: 'browser', tier: 'intermediate', requires: ['c.oop', 'c.git'], navTo: 'web', state: lock,
      desc: 'A subject of its own: pages, styling, state, data and everything it takes to ship something people can open.' },
    { id: 'c.algo', name: 'Algorithms & Data Structures', icon: 'graph-nodes', tier: 'advanced', requires: ['c.ds'], navTo: 'algorithms', state: lock,
      desc: 'A subject of its own: the structures worth knowing and the moves that run over them.' },
    { id: 'c.sys', name: 'Systems', icon: 'kernel', tier: 'advanced', requires: ['c.perf', 'c.async'], navTo: 'systems', state: lock,
      desc: 'A subject of its own: what the machine is actually doing underneath the code you write.' },
    { id: 'c.data', name: 'Data Science', icon: 'dataset', tier: 'advanced', requires: ['c.ds', 'c.lists'], navTo: 'data-science', state: lock,
      desc: 'A subject of its own: getting an honest answer out of a table of numbers, and knowing when you have not.' },
    { id: 'c.db', name: 'Databases', icon: 'database', tier: 'intermediate', requires: ['c.files'], navTo: 'databases', state: lock,
      desc: 'A subject of its own: where the data lives, how it is shaped, and how to ask it things.' },
    { id: 'c.sec', name: 'Cybersecurity', icon: 'shield', tier: 'advanced', requires: ['c.err', 'c.git'], navTo: 'cybersecurity', state: lock,
      desc: 'A subject of its own: what breaks, why it breaks, and the habits that stop it breaking here.' },
    { id: 'c.robotics', name: 'Competitive Robotics', icon: 'automation', tier: 'advanced', requires: ['c.oop', 'c.debug'], navTo: 'robotics', state: lock,
      desc: 'A subject of its own: FRC and VEX — build season, and the robot that never stops working.' },
  ],
};
