import type { SubjectTree } from './types';
import { done, prog, open, lock } from './types';

export const MATH: SubjectTree = {
  id: 'mathematics',
  title: 'Mathematics',
  blurb: 'The ladder most other subjects are quietly standing on.',
  group: 'Maths and science',
  nodes: [
    { id: 'm.arith', name: 'Arithmetic', icon: 'arithmetic', tier: 'foundation', core: true, state: done, percent: 100, xp: 1200,
      desc: 'The four operations, done reliably and with a sense of roughly what the answer should be. That estimate is the actual skill — it is what catches a mistake before it travels.' },
    { id: 'm.order', name: 'Order of Operations', icon: 'checklist', tier: 'foundation', requires: ['m.arith'], state: done, percent: 100, xp: 1000,
      desc: 'The agreed order for evaluating an expression, so one string of symbols means one thing. Small, but every algebraic error later either respects it or comes from ignoring it.' },
    { id: 'm.fractions', name: 'Fractions', icon: 'fractions', tier: 'foundation', requires: ['m.arith'], state: done, percent: 100, xp: 1300,
      desc: 'Parts of a whole, and arithmetic where the denominators have to agree first. Fluency here quietly decides how hard algebra feels two years later.' },
    { id: 'm.decimals', name: 'Decimals & Percents', icon: 'percent', tier: 'foundation', requires: ['m.fractions'], state: done, percent: 95, xp: 1100,
      desc: 'Three ways of writing the same quantity, and moving between them without thinking. Percentage change is the one people keep getting wrong, in both directions.' },
    { id: 'm.negatives', name: 'Negative Numbers', icon: 'negative-numbers', tier: 'foundation', requires: ['m.order'], state: prog, percent: 85, xp: 1100,
      desc: 'Quantities below zero and what the operations do to them. Signs are the single most common source of a wrong answer in otherwise correct algebra.' },
    { id: 'm.algebra', name: 'Algebra', icon: 'algebra-x', tier: 'beginner', core: true, requires: ['m.fractions', 'm.negatives'], state: prog, percent: 80, xp: 2000,
      desc: 'Letters standing in for numbers, and rearranging while keeping both sides equal. The shift is from computing an answer to manipulating a relationship, which is what makes the rest of mathematics possible.' },
    { id: 'm.linear', name: 'Linear Equations', icon: 'linear-equation', tier: 'beginner', requires: ['m.algebra'], state: prog, percent: 70, xp: 1600,
      desc: 'Equations whose graph is a straight line, and solving one or several at once. Slope and intercept are worth being able to read off in either direction without hesitation.' },
    { id: 'm.inequalities', name: 'Inequalities', icon: 'equations', tier: 'beginner', requires: ['m.linear'], state: open, percent: 30, xp: 1400,
      desc: 'Relationships that are less-than rather than equal, and the one rule that surprises everyone: multiplying by a negative flips the sign.' },
    { id: 'm.geometry', name: 'Geometry', icon: 'geometry', tier: 'beginner', requires: ['m.arith'], state: prog, percent: 60, xp: 1800,
      desc: 'Shape, angle, area and distance, and proving something is true for every case rather than the one you drew. Drawing the diagram first is not a study tip, it is the method.' },
    { id: 'm.coords', name: 'Coordinate Geometry', icon: 'coordinate-plane', tier: 'intermediate', requires: ['m.geometry', 'm.linear'], state: open, percent: 25, xp: 1700,
      desc: 'Shapes described by equations on a grid, which lets algebra answer geometric questions. The bridge that makes both subjects considerably more powerful than either alone.' },
    { id: 'm.quadratics', name: 'Quadratics', icon: 'parabola', tier: 'intermediate', requires: ['m.linear'], state: open, percent: 20, xp: 1800,
      desc: 'Equations with a squared term, and the parabola they draw. Three routes to a solution — factoring, completing the square, the formula — and knowing which is quickest matters.' },
    { id: 'm.functions', name: 'Functions', icon: 'functions-graph', tier: 'intermediate', core: true, requires: ['m.quadratics'], state: open, percent: 35, xp: 2100,
      desc: 'A rule taking each input to exactly one output, and the graph as its picture. Domain, range, composition and inverses are the vocabulary the whole of later mathematics assumes you have.' },
    { id: 'm.exponents', name: 'Exponents & Logarithms', icon: 'logarithm', tier: 'intermediate', requires: ['m.functions'], state: lock, percent: 0, xp: 1900,
      desc: 'Repeated multiplication and the operation that undoes it. Logs turn multiplication into addition, which is why they appear everywhere from complexity to acoustics.' },
    { id: 'm.trig', name: 'Trigonometry', icon: 'trigonometry', tier: 'intermediate', requires: ['m.coords', 'm.functions'], state: open, percent: 15, xp: 2200,
      desc: 'Ratios in a right triangle that turn out to describe every wave. Derive the unit circle once rather than memorising the table and the identities stop being arbitrary.' },
    { id: 'm.stats', name: 'Statistics', icon: 'statistics', tier: 'intermediate', requires: ['m.decimals'], state: open, percent: 20, xp: 1900,
      desc: 'Describing data honestly: what is typical, how spread out it is, and how sure you are allowed to be. Most misuse is not bad arithmetic but a chart or an average answering a question nobody asked.' },
    { id: 'm.combinatorics', name: 'Counting & Combinatorics', icon: 'puzzle', tier: 'advanced', requires: ['m.algebra'], state: lock, percent: 0, xp: 2000,
      desc: 'Counting arrangements without listing them. Whether order matters and whether repetition is allowed are the two questions that decide which formula applies.' },
    { id: 'm.prob', name: 'Probability', icon: 'probability', tier: 'advanced', requires: ['m.stats', 'm.combinatorics'], recommends: ['m.functions'], state: lock, percent: 0, xp: 2000,
      desc: 'How likely something is, given what you already know. Conditional probability is where intuition fails hardest, which is why the classic paradoxes are all built from it.' },
    { id: 'm.sequences', name: 'Sequences & Series', icon: 'series', tier: 'advanced', requires: ['m.exponents'], state: lock, percent: 0, xp: 2100,
      desc: 'Ordered lists of numbers and what happens when you add them all up. Whether an infinite sum settles on a value is the question calculus later answers properly.' },
    { id: 'm.proof', name: 'Proof', icon: 'shield', tier: 'advanced', requires: ['m.geometry', 'm.algebra'], state: lock, percent: 0, xp: 2400,
      desc: 'Establishing that something is true for every case, not merely the ones you tried. Induction, contradiction and construction are the three moves worth being fluent in.' },
    { id: 'm.linalg', name: 'Linear Algebra', icon: 'matrices', tier: 'expert', requires: ['m.coords', 'm.functions'], navTo: 'linear-algebra', state: lock,
      desc: 'A subject of its own: vectors, the transformations that move them, and treating a whole system of equations as one object.' },
    { id: 'm.precalc', name: 'Precalculus', icon: 'precalculus', tier: 'advanced', requires: ['m.trig', 'm.exponents'], state: lock, percent: 0, xp: 2300,
      desc: 'The last tightening of functions, graphs and algebra before limits begin. Not a subject so much as everything you will need fluently the moment calculus starts.' },
    { id: 'm.calc', name: 'Calculus', icon: 'calculus', tier: 'expert', requires: ['m.precalc'], navTo: 'calculus', state: lock,
      desc: 'A subject of its own: rates of change, areas under curves, and the limit that sits underneath both.' },
    { id: 'm.statx', name: 'Statistics & Probability', icon: 'distribution', tier: 'expert', requires: ['m.prob'], navTo: 'statistics', state: lock,
      desc: 'A subject of its own: reasoning about what you cannot see all of, and saying how sure you are.' },
    { id: 'm.disc', name: 'Discrete Mathematics', icon: 'logic', tier: 'expert', requires: ['m.proof'], navTo: 'discrete', state: lock,
      desc: 'A subject of its own: logic, sets, counting and proof — the maths computing is written in.' },
    { id: 'm.compmath', name: 'Competition Mathematics', icon: 'trophy', tier: 'expert', requires: ['m.proof', 'm.combinatorics'], navTo: 'competition-math', state: lock,
      desc: 'A subject of its own: AMC, AIME and olympiad — choosing the method, against a clock.' },
  ],
};
