import type { SubjectTree } from './types';
import { done, prog, open, lock } from './types';

export const MUSIC: SubjectTree = {
  id: 'music',
  title: 'Music',
  blurb: 'Ear, hands and theory — the three that have to grow together.',
  group: 'Creative',
  nodes: [
    { id: 'mu.pulse', name: 'Pulse & Tempo', icon: 'metronome', tier: 'foundation', core: true, state: done, percent: 100, xp: 1000,
      desc: 'Feeling a steady beat and holding it without drifting. Everything rhythmic sits on this, and playing with a metronome exposes immediately how steady you actually are.' },
    { id: 'mu.rhythm', name: 'Rhythm', icon: 'rhythm', tier: 'foundation', core: true, requires: ['mu.pulse'], state: done, percent: 100, xp: 1200,
      desc: 'Dividing the beat into patterns and placing notes precisely inside it. Counting out loud feels childish and remains the fastest way to fix a rhythm you keep fluffing.' },
    { id: 'mu.notes', name: 'Reading Notes', icon: 'staff', tier: 'foundation', core: true, requires: ['mu.pulse'], state: prog, percent: 70, xp: 1500,
      desc: 'Turning a position on the stave into a pitch without counting up from the bottom line. Recognition needs to become instant, because the moment it does, sight reading stops being arithmetic.' },
    { id: 'mu.dynamics', name: 'Dynamics & Articulation', icon: 'dynamics', tier: 'beginner', requires: ['mu.rhythm'], state: prog, percent: 50, xp: 1200,
      desc: 'How loud, and how each note is started and released. This is most of what separates a performance from a correct sequence of pitches.' },
    { id: 'mu.scales', name: 'Scales', icon: 'scales', tier: 'beginner', requires: ['mu.notes'], state: prog, percent: 55, xp: 1700,
      desc: 'The ordered set of pitches a piece draws from, and the pattern of steps that defines each type. Practising them is partly theory and partly the most efficient technique exercise there is.' },
    { id: 'mu.intervals', name: 'Intervals', icon: 'intervals', tier: 'beginner', requires: ['mu.notes'], state: open, percent: 30, xp: 1600,
      desc: 'The distance between two pitches, named by size and quality. Attaching each one to a song you already know is the trick that makes them recognisable by ear rather than by counting.' },
    { id: 'mu.keys', name: 'Keys & Signatures', icon: 'key-signature', tier: 'intermediate', requires: ['mu.scales'], state: open, percent: 20, xp: 1800,
      desc: 'Which notes a piece has agreed to use, declared once at the start. The circle of fifths turns fifteen separate facts into one picture worth being able to draw from memory.' },
    { id: 'mu.chords', name: 'Chords', icon: 'chords', tier: 'intermediate', core: true, requires: ['mu.scales', 'mu.intervals'], state: lock, percent: 0, xp: 2000,
      desc: 'Three or more notes sounding together, built by stacking intervals. Major, minor, diminished and augmented are four different feelings produced by moving one note a semitone.' },
    { id: 'mu.inversions', name: 'Inversions', icon: 'loops', tier: 'intermediate', requires: ['mu.chords'], state: lock, percent: 0, xp: 1700,
      desc: 'The same chord with a different note at the bottom. What changes is not the harmony but the smoothness of the movement, which is what voice leading is about.' },
    { id: 'mu.progressions', name: 'Progressions', icon: 'progressions', tier: 'intermediate', requires: ['mu.inversions', 'mu.keys'], state: lock, percent: 0, xp: 2100,
      desc: 'Chords in sequence, and why a handful of orders keep reappearing across centuries and genres. Tension and release is the whole mechanism, and cadences are where it resolves.' },
    { id: 'mu.ear', name: 'Ear Training', icon: 'ear-training', tier: 'advanced', requires: ['mu.intervals'], recommends: ['mu.chords'], state: lock, percent: 0, xp: 2200,
      desc: 'Naming what you heard: intervals, chord qualities, and eventually whole progressions. Five focused minutes daily beats an hour a week, and it is the skill the other seven are worth less without.' },
    { id: 'mu.sightread', name: 'Sight Reading', icon: 'book', tier: 'advanced', requires: ['mu.notes', 'mu.dynamics'], state: lock, percent: 0, xp: 2000,
      desc: 'Playing something you have never seen, in time, without stopping. Improved only by reading new material constantly and accepting that it will be rough.' },
    { id: 'mu.modes', name: 'Modes', icon: 'modes', tier: 'advanced', requires: ['mu.keys'], state: lock, percent: 0, xp: 2000,
      desc: 'The same seven notes started from a different degree, giving seven distinct colours. Hearing dorian as its own thing rather than as a displaced major scale is the point.' },
    { id: 'mu.harmony', name: 'Harmony', icon: 'harmony', tier: 'advanced', requires: ['mu.progressions'], state: lock, percent: 0, xp: 2400,
      desc: 'How independent lines combine, and the conventions that make some combinations sound intentional. Voice leading — moving each part as little as possible — explains most of the rules.' },
    { id: 'mu.form', name: 'Musical Form', icon: 'layers', tier: 'advanced', requires: ['mu.progressions'], state: lock, percent: 0, xp: 1900,
      desc: 'The architecture of a piece: what repeats, what contrasts, and where it returns. Hearing structure while listening is what makes long pieces feel navigable rather than endless.' },
    { id: 'mu.improv', name: 'Improvisation', icon: 'spark', tier: 'expert', requires: ['mu.ear', 'mu.modes'], state: lock, percent: 0, xp: 2600,
      desc: 'Making music in real time inside a set of constraints. It is far less mysterious than it looks: a vocabulary of phrases, deep familiarity with the changes, and the nerve to commit.' },
    { id: 'mu.composition', name: 'Composition', icon: 'idea', tier: 'expert', requires: ['mu.harmony', 'mu.form'], state: lock, percent: 0, xp: 2700,
      desc: 'Writing music that goes somewhere. Craft rather than inspiration — a good idea developed properly beats four good ideas laid end to end.' },
    { id: 'mu.performance', name: 'Performance', icon: 'trophy', tier: 'mastery', requires: ['mu.sightread', 'mu.improv'], state: lock, percent: 0, xp: 3000,
      desc: 'Playing for other people, under pressure, and communicating something. A separate skill from playing well alone, and one that only performing actually trains.' },
    { id: 'mu.guitar', name: 'Guitar', icon: 'guitar', tier: 'beginner', requires: ['mu.rhythm'], navTo: 'guitar', state: lock,
      desc: 'A subject of its own: both hands, the neck, and the gap between knowing a chord and landing it.' },
    { id: 'mu.piano', name: 'Piano', icon: 'piano-keys', tier: 'beginner', requires: ['mu.notes'], navTo: 'piano', state: lock,
      desc: 'A subject of its own: two hands doing different jobs, and the reading that keeps up with them.' },
    { id: 'mu.voice', name: 'Singing', icon: 'breath', tier: 'beginner', requires: ['mu.intervals'], navTo: 'voice', state: lock,
      desc: 'A subject of its own: breath, pitch and the instrument you cannot see or put down.' },
    { id: 'mu.prod', name: 'Music Production', icon: 'daw', tier: 'advanced', requires: ['mu.form'], navTo: 'production', state: lock,
      desc: 'A subject of its own: turning parts into a record — arrangement, sound, and the mix coming last.' },
    { id: 'mu.stage', name: 'Performance & Auditions', icon: 'audience', tier: 'advanced', requires: ['mu.performance', 'mu.sightread'], navTo: 'performance', state: lock,
      desc: 'A subject of its own: recitals, juries and competitions — playing it once, in front of people.' },
  ],
};
