import type { SubjectTree } from './types';
import { open, lock } from './types';

export const SYSTEMS: SubjectTree = {
  id: 'systems',
  title: 'Systems',
  blurb: 'What the machine is actually doing underneath the code you write.',
  parent: 'coding',
  nodes: [
    { id: 's.memory', name: 'Memory', icon: 'memory', tier: 'intermediate', core: true, state: open, percent: 25, xp: 2000,
      desc: 'Where values actually live and what it costs to reach them. Once you can picture memory as one long addressable strip, a lot of otherwise arbitrary performance advice becomes obvious.' },
    { id: 's.stackheap', name: 'Stack & Heap', icon: 'layers', tier: 'intermediate', requires: ['s.memory'], state: open, percent: 15, xp: 1900,
      desc: 'Two places a program keeps things: a fast, automatically managed stack for call frames, and a flexible heap you allocate from. Which one a value lives on explains its lifetime and most of its cost.' },
    { id: 's.pointers', name: 'Pointers & References', icon: 'pointers', tier: 'intermediate', requires: ['s.memory'], state: open, percent: 10, xp: 2100,
      desc: 'A value that is the address of another value. Every "why did changing this change that" surprise in any language traces back to whether you copied the thing or a reference to it.' },
    { id: 's.processes', name: 'Processes', icon: 'process', tier: 'intermediate', requires: ['s.stackheap'], state: lock, percent: 0, xp: 1900,
      desc: 'A running program as the operating system sees it, with its own memory and its own view of the machine. Isolation is the point: one crashing process should not take the others with it.' },
    { id: 's.files', name: 'File Systems', icon: 'filesystem', tier: 'intermediate', requires: ['s.processes'], state: lock, percent: 0, xp: 1700,
      desc: 'How bytes are named, found and kept between runs. Paths, permissions and the fact that a write is not durable until it is flushed account for most surprises here.' },
    { id: 's.threads', name: 'Threads', icon: 'threads', tier: 'advanced', requires: ['s.processes'], state: lock, percent: 0, xp: 2200,
      desc: 'Several lines of execution inside one process, sharing its memory. The sharing is what makes threads fast and what makes them dangerous.' },
    { id: 's.concurrency', name: 'Concurrency', icon: 'concurrency', tier: 'advanced', requires: ['s.threads'], state: lock, percent: 0, xp: 2600,
      desc: 'Getting correct results when things happen at once or in an unpredictable order. Race conditions are the defining hazard: the bug is real, intermittent, and disappears when you look at it.' },
    { id: 's.locks', name: 'Locks & Deadlock', icon: 'locked', tier: 'expert', requires: ['s.concurrency'], state: lock, percent: 0, xp: 2500,
      desc: 'Protecting shared state, and the new failure that protection creates: two holders each waiting on the other forever. Consistent lock ordering is the cheapest cure.' },
    { id: 's.io', name: 'Buffered I/O', icon: 'buffer', tier: 'advanced', requires: ['s.files'], state: lock, percent: 0, xp: 1800,
      desc: 'Why reading a file one byte at a time is thousands of times slower than reading it in blocks. Buffering is the general trick of paying a large fixed cost rarely instead of a small one constantly.' },
    { id: 's.net', name: 'Networking', icon: 'network', tier: 'advanced', requires: ['s.io'], state: lock, percent: 0, xp: 2300,
      desc: 'Two machines agreeing how to say something to each other, in layers. Knowing what DNS, TCP and TLS each did before your request left is what makes network debugging tractable.' },
    { id: 's.sockets', name: 'Sockets', icon: 'api', tier: 'advanced', requires: ['s.net'], state: lock, percent: 0, xp: 2200,
      desc: 'The actual programming interface behind every network call — open, write, read, close. Speaking HTTP by hand over one is the fastest way to stop treating the web as magic.' },
    { id: 's.server', name: 'Servers', icon: 'server', tier: 'advanced', requires: ['s.sockets', 's.concurrency'], state: lock, percent: 0, xp: 2400,
      desc: 'A program that waits for requests and answers many of them at once. How it handles that concurrency — threads, processes or an event loop — shapes everything about how it scales.' },
    { id: 's.db', name: 'Databases', icon: 'database', tier: 'advanced', requires: ['s.server'], state: lock, percent: 0, xp: 2500,
      desc: 'Storing data so it can be queried flexibly and survives a crash halfway through a write. Transactions are the promise that a group of changes either all happen or none do.' },
    { id: 's.indexes', name: 'Indexes & Query Plans', icon: 'searching', tier: 'expert', requires: ['s.db'], state: lock, percent: 0, xp: 2600,
      desc: 'Why one query returns instantly and an almost identical one takes a minute. Reading the plan tells you what the database decided to do, which is usually not what you assumed.' },
    { id: 's.caching', name: 'Caching', icon: 'cache', tier: 'advanced', requires: ['s.db'], state: lock, percent: 0, xp: 2300,
      desc: 'Keeping a copy of an expensive answer close by. Easy to add and hard to retire — deciding when a cached copy stops being true is the entire difficulty.' },
    { id: 's.scaling', name: 'Scaling', icon: 'cloud', tier: 'mastery', requires: ['s.caching', 's.indexes'], state: lock, percent: 0, xp: 3000,
      desc: 'Serving far more load than one machine can, and accepting the trade-offs that forces. Almost every hard distributed-systems problem starts the moment a second copy of the data exists.' },
    { id: 's.netx', name: 'Networks & Protocols', icon: 'packet', tier: 'advanced', requires: ['s.sockets'], navTo: 'networking', state: lock,
      desc: 'A subject of its own: how one machine reaches another, layer by layer, and where it goes wrong.' },
  ],
};
