import type { SubjectTree } from './types';
import { done, prog, open, lock } from './types';

export const WEB: SubjectTree = {
  id: 'web',
  title: 'Web Development',
  blurb: 'From a first page to something shipped, styled, signed in and fast.',
  parent: 'coding',
  nodes: [
    { id: 'w.html', name: 'HTML', icon: 'html', tier: 'foundation', core: true, state: done, percent: 100, xp: 1400,
      desc: 'The structure of a page: what is a heading, a list, a button, a form. Choosing the tag that means the right thing is what gives you working keyboard support and screen-reader behavior for free.' },
    { id: 'w.css', name: 'CSS', icon: 'css', tier: 'foundation', core: true, requires: ['w.html'], state: done, percent: 100, xp: 1900,
      desc: 'How the page looks, written as rules that match elements. The cascade and specificity decide which rule wins when several apply, and not knowing those two is why CSS feels random before it feels precise.' },
    { id: 'w.layout', name: 'Layout & Flexbox', icon: 'layout', tier: 'beginner', requires: ['w.css'], state: prog, percent: 70, xp: 1800,
      desc: 'Arranging boxes along a row, a column or a grid. Flexbox handles one direction and grid handles two; picking the wrong one is the usual reason a layout needs a fight to behave.' },
    { id: 'w.responsive', name: 'Responsive Design', icon: 'responsive', tier: 'beginner', requires: ['w.layout'], state: open, percent: 25, xp: 1600,
      desc: 'One page that works from a phone to a wide monitor. The good version comes from flexible units and content that reflows naturally, with breakpoints as a last resort rather than the plan.' },
    { id: 'w.dom', name: 'The DOM', icon: 'dom', tier: 'beginner', requires: ['w.html'], state: prog, percent: 55, xp: 1700,
      desc: 'The live tree of the page as a program can see it: find an element, read it, change it, listen for what a person does. Everything interactive on the web is ultimately this.' },
    { id: 'w.forms', name: 'Forms & Validation', icon: 'form', tier: 'beginner', requires: ['w.dom'], state: open, percent: 20, xp: 1500,
      desc: 'Collecting input and telling someone clearly when it is wrong. Validate in the browser for speed and on the server for safety — the browser copy is a courtesy, never the guarantee.' },
    { id: 'w.json', name: 'JSON & Data Shapes', icon: 'package', tier: 'beginner', requires: ['w.dom'], state: open, percent: 30, xp: 1300,
      desc: 'The format almost every web API speaks, and the habit of knowing exactly what shape you expect back. Most fetch bugs are shape bugs rather than network bugs.' },
    { id: 'w.a11y', name: 'Accessibility', icon: 'available', tier: 'intermediate', requires: ['w.forms'], state: lock, percent: 0, xp: 1900,
      desc: 'Making the page usable by keyboard, screen reader and anyone not using it the way you do. Most of it is choosing correct HTML and keeping focus visible, not adding extra machinery.' },
    { id: 'w.http', name: 'HTTP & Fetch', icon: 'http', tier: 'intermediate', requires: ['w.json'], state: open, percent: 15, xp: 1600,
      desc: 'How a browser asks another machine for something: method, path, headers, status, body. Knowing what a 401 means as distinct from a 403 saves hours you would otherwise spend guessing.' },
    { id: 'w.state', name: 'Client State', icon: 'client-state', tier: 'intermediate', requires: ['w.dom'], state: open, percent: 10, xp: 1800,
      desc: 'Everything the page currently knows, and keeping it true as things change. The discipline is to store each fact once and derive the rest, because two copies eventually disagree.' },
    { id: 'w.react', name: 'Components', icon: 'components', tier: 'intermediate', core: true, requires: ['w.state', 'w.layout'], state: lock, percent: 0, xp: 2400,
      desc: 'Building an interface from small pieces that own their own markup, style and behavior. The payoff is that you can reason about, test and reuse one piece without loading the whole page into your head.' },
    { id: 'w.props', name: 'Props & Composition', icon: 'puzzle', tier: 'intermediate', requires: ['w.react'], state: lock, percent: 0, xp: 1700,
      desc: 'Passing data down and composing small components into bigger ones. Getting the boundaries right — who owns which piece of state — is most of what makes a component tree pleasant or painful.' },
    { id: 'w.routing', name: 'Routing', icon: 'routing', tier: 'intermediate', requires: ['w.react'], state: lock, percent: 0, xp: 1500,
      desc: 'One address per screen, so the back button, a refresh and a pasted link all do what a person expects. It is what makes an app feel like part of the web rather than a page that swallowed one.' },
    { id: 'w.build', name: 'Build Tools', icon: 'compile', tier: 'intermediate', requires: ['w.props'], state: lock, percent: 0, xp: 1500,
      desc: 'The step that turns the source you write into files a browser can load quickly. Worth understanding rather than copying: the config is where most mysterious failures live.' },
    { id: 'w.effects', name: 'Effects & Lifecycles', icon: 'timer', tier: 'advanced', requires: ['w.props'], state: lock, percent: 0, xp: 2100,
      desc: 'Running work when something appears, changes or goes away — and cleaning up after it. Almost every stubborn interface bug is an effect that ran too often or never got torn down.' },
    { id: 'w.apis', name: 'Talking to APIs', icon: 'api', tier: 'advanced', requires: ['w.http', 'w.effects'], state: lock, percent: 0, xp: 2000,
      desc: 'Loading real data into a real interface, including while it is still loading and when it fails. An empty result and an error are different states and a good screen never confuses them.' },
    { id: 'w.auth', name: 'Auth & Sessions', icon: 'auth', tier: 'advanced', requires: ['w.apis'], state: lock, percent: 0, xp: 2200,
      desc: 'Knowing who is asking and keeping that true for the rest of the visit. The rule that matters: the browser decides what to show, the server decides what is allowed.' },
    { id: 'w.perf', name: 'Web Performance', icon: 'energy', tier: 'advanced', requires: ['w.build'], state: lock, percent: 0, xp: 2000,
      desc: 'Making a page load and respond quickly on a normal connection and a normal phone. Measure first: the biggest wins are usually shipping less code and not blocking the first paint.' },
    { id: 'w.test', name: 'Testing the UI', icon: 'checklist', tier: 'advanced', requires: ['w.apis'], state: lock, percent: 0, xp: 1900,
      desc: 'Checking that a screen does what a person needs, driven the way a person drives it. Test behavior rather than internals, or every refactor breaks a hundred tests that were describing the wrong thing.' },
    { id: 'w.deploy', name: 'Deploying', icon: 'deploy', tier: 'advanced', requires: ['w.auth', 'w.routing'], state: lock, percent: 0, xp: 1900,
      desc: 'Getting it onto a machine that is not yours and keeping it running. The goal is that shipping is boring: one command, repeatable, and reversible when it goes wrong.' },
    { id: 'w.security', name: 'Web Security', icon: 'security', tier: 'expert', requires: ['w.auth', 'w.test'], state: lock, percent: 0, xp: 2600,
      desc: 'The handful of attacks every web app faces — injected scripts, forged requests, leaked tokens — and the specific habits that prevent each. Assume every byte from the browser is hostile until proven otherwise.' },
  ],
};
